/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package posi.sys.admin;

import java.awt.event.ActionEvent;
import javax.swing.SwingConstants;

/**
 *
 * @author Aquarius
 */
public class user_mng_en extends posi.sys.expeditors.popup {
    private String user_id;
    
    private javax.swing.JPanel panel = new javax.swing.JPanel();
    
    private javax.swing.JTextField emp_id, fname, mname, lname, dob, idnum, serail_num, 
            krapin,nssfnum,date_enrolled, rank,salary;
    
    private javax.swing.JComboBox type;
    
    private javax.swing.JLabel emp_id_label, fname_label, mname_label, lname_label, dob_label, idnum_label, serail_num_label, 
            krapin_label,nssfnum_label,date_enrolled_label, rank_label,salary_label,type_label;
    
    private javax.swing.JButton next, prev, cancel, save, button, change_pass;
    
    private Object [] data;
    
    private posi.sys.all.expeditors.database.db_connect db = new posi.sys.all.expeditors.database.db_connect();
    
    private java.sql.ResultSet rs;
    
    public user_mng_en(){
        super(new java.awt.Dimension(450,660),"Add user");
        
        content();
        
        button.setActionCommand("save");
        
        emp_id.setText("Autogenerated");
        
        deactivate_btns();
    }
    
    public user_mng_en(String index){
        super(new java.awt.Dimension(450,630),"Edit user");
        
        this.user_id = index;
        
        content();
        
        button.setActionCommand("update");
        
        populate();
    }
    
    public final void deactivate_btns(){
        next.setEnabled(false);
        prev.setEnabled(false);
        change_pass.setEnabled(false);
    }
    
    public final void populate(){
        Object data_ [][];
        if (!"".equals(this.user_id)){
            String sql = "SELECT * FROM employees";
            //System.out.print(sql);
            rs = db.Query(sql);
            try {
                boolean cont = true;
                
                while( rs.next() && cont == true){                     
                    if( rs.getString(1).equals ( user_id ) ) { 
                        populate(rs);
                        cont = false;
                    }
                }
                //ifDataAvailable = (data.length > 0 && data.length <= 1)? true : false ;
                //this.renderContent( false );
            } catch (java.sql.SQLException ex) {
                System.err.println("Error"+ ex.getMessage());
            }
        }
    }
    
    private void populate(java.sql.ResultSet rs){
        try {
            emp_id.setText( rs.getString(1) );
            fname.setText( rs.getString(2) );
            mname.setText( rs.getString(3) );
            lname.setText( rs.getString(4) );            
            dob.setText( rs.getString(5) );
            idnum.setText( rs.getString(6) );            
            serail_num.setText( rs.getString(7) );
            krapin.setText( rs.getString(8) );
            nssfnum.setText( rs.getString(9) );
            date_enrolled.setText( rs.getString(10) );
            rank.setText( rs.getString(11) );
            salary.setText( rs.getString(12) );
            type.setSelectedIndex(Integer.parseInt(rs.getString(14)));
        }catch (java.sql.SQLException ex) {
                System.err.println("Error"+ ex.getMessage());
            }
                        
    }
    public final void content(){
        javax.swing.JPanel pane;
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        emp_id_label = new javax.swing.JLabel("Employer ID: ", SwingConstants.RIGHT);
        emp_id_label.setPreferredSize(new java.awt.Dimension(100, 30));
        emp_id = new javax.swing.JTextField(14);
        emp_id.setPreferredSize(new java.awt.Dimension(150, 30));
        emp_id.setEditable( false );
        pane.add(emp_id_label);
        pane.add(emp_id);
        panel.add(pane);

        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        fname_label = new javax.swing.JLabel("First name: ", SwingConstants.RIGHT);
        fname_label.setPreferredSize(new java.awt.Dimension(100, 30));
        fname = new javax.swing.JTextField(20);
        fname.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(fname_label);
        pane.add(fname);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        mname_label = new javax.swing.JLabel("Middle name: ", SwingConstants.RIGHT);
        mname_label.setPreferredSize(new java.awt.Dimension(100, 30));
        mname = new javax.swing.JTextField(20);
        mname.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(mname_label);
        pane.add(mname);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        lname_label = new javax.swing.JLabel("Last name: ", SwingConstants.RIGHT);
        lname_label.setPreferredSize(new java.awt.Dimension(100, 30));
        lname = new javax.swing.JTextField(20);
        lname.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(lname_label);
        pane.add(lname);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        dob_label = new javax.swing.JLabel("DOB: ", SwingConstants.RIGHT);
        dob_label.setPreferredSize(new java.awt.Dimension(100, 30));
        dob = new javax.swing.JTextField(20);
        dob.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(dob_label);
        pane.add(dob);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        idnum_label = new javax.swing.JLabel("ID num: ", SwingConstants.RIGHT);
        idnum_label.setPreferredSize(new java.awt.Dimension(100, 30));
        idnum = new javax.swing.JTextField(20);
        idnum.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(idnum_label);
        pane.add(idnum);
        panel.add(pane);
       
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        serail_num_label = new javax.swing.JLabel("Serial num: ", SwingConstants.RIGHT);
        serail_num_label.setPreferredSize(new java.awt.Dimension(100, 30));
        serail_num = new javax.swing.JTextField(20);
        serail_num.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(serail_num_label);
        pane.add(serail_num);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        krapin_label = new javax.swing.JLabel("KRA pin: ", SwingConstants.RIGHT);
        krapin_label.setPreferredSize(new java.awt.Dimension(100, 30));
        krapin = new javax.swing.JTextField(20);
        krapin.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(krapin_label);
        pane.add(krapin);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        nssfnum_label = new javax.swing.JLabel("NSSF num: ", SwingConstants.RIGHT);
        nssfnum_label.setPreferredSize(new java.awt.Dimension(100, 30));
        nssfnum = new javax.swing.JTextField(20);
        nssfnum.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(nssfnum_label);
        pane.add(nssfnum);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        date_enrolled_label = new javax.swing.JLabel("Date enrolled: ", SwingConstants.RIGHT);
        date_enrolled_label.setPreferredSize(new java.awt.Dimension(100, 30));
        date_enrolled = new javax.swing.JTextField(20);
        date_enrolled.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(date_enrolled_label);
        pane.add(date_enrolled);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        rank_label = new javax.swing.JLabel("Rank: ", SwingConstants.RIGHT);
        rank_label.setPreferredSize(new java.awt.Dimension(100, 30));
        rank = new javax.swing.JTextField(20);
        rank.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(rank_label);
        pane.add(rank);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        salary_label = new javax.swing.JLabel("Salary: ", SwingConstants.RIGHT);
        salary_label.setPreferredSize(new java.awt.Dimension(100, 30));
        salary = new javax.swing.JTextField(20);
        salary.setPreferredSize(new java.awt.Dimension(200, 30));
        pane.add(salary_label);
        pane.add(salary);
        panel.add(pane);
        
        String sql = "SELECT employee_role_name FROM employee_roles;";
        data = db.getColData(sql);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 35));
        type_label = new javax.swing.JLabel("Type: ", SwingConstants.RIGHT);
        type_label.setPreferredSize(new java.awt.Dimension(100, 30));
        type = new javax.swing.JComboBox( data );
        type.setPreferredSize(new java.awt.Dimension(150, 30));
        pane.add(type_label);
        pane.add(type);
        panel.add(pane);
        
        pane = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        pane.setPreferredSize(new java.awt.Dimension(getWidth() - 10, 40));
        
        prev = new javax.swing.JButton( "<< Previous" );
        prev.addActionListener(new Action());
        pane.add( prev );
        
        button = new javax.swing.JButton( "Save" );
        button.addActionListener(new Action());
        pane.add( button );
        
        cancel = new javax.swing.JButton( "Cancel" );
        cancel.addActionListener(new Action());
        pane.add( cancel );
        
        next = new javax.swing.JButton( "Next >>" );
        next.addActionListener(new Action());
        pane.add( next );
        
        panel.add(pane);        
        
        change_pass = new javax.swing.JButton( " Change password " );
        change_pass.addActionListener(new Action());
        panel.add( change_pass );
        
        add(panel);
    }
    
    public static void main(String [] args){
        new user_mng_en().setVisible(true);
    }
    
    private void update(){
        String sql = "UPDATE employees SET "
                + "employee_fname = '"+fname.getText()+"', "
                + "employee_mname = '"+mname.getText()+"',"
                + "employee_lname = '"+lname.getText()+"', "
                + "employee_dob = '"+dob.getText()+"',"
                + "employee_idnum = '"+idnum.getText()+"',"
                + "employee_serial_num = '" + serail_num.getText() + "',"
                + "employee_kra_pin = '"+ krapin.getText() + "',"
                + "employee_nssf_num = '"+ nssfnum.getText()  +"',"
                + "employee_date_enrolled = '"+date_enrolled.getText()+"',"
                + "employee_rank = '"+rank.getText()+"',"
                + "employee_salary = '"+ salary.getText() +"',"
                + "employee_role_id = '"+type.getSelectedIndex()+"'"
                
                + "WHERE employee_id = '"+emp_id.getText()+"';";
         
        //System.out.println(sql);
         
        if(db.addNew(sql)){
            javax.swing.JOptionPane.showMessageDialog(null,"User has been updated","Record added!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            admin.user_management();
            
            dispose();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null,"User has failed to be updated","Record adding error!",javax.swing.JOptionPane.ERROR_MESSAGE);        
        }
    }
    
    private void save (){
        String sql = "INSERT INTO employees"
                + "(employee_id,employee_fname,employee_mname,employee_lname,employee_dob,employee_idnum,employee_serial_num,employee_kra_pin,"
                 +  "employee_nssf_num,employee_date_enrolled,employee_rank,employee_salary,employee_role_id)"
                + "VALUES(NULL,'"+fname.getText() +"', '"+mname.getText()+"','"+ lname.getText() +"','"+ dob.getText() +"','"+ idnum.getText() + "', '"
                +serail_num.getText() + "', '" +krapin.getText() +"','"+nssfnum.getText() +"','"+date_enrolled.getText() +"','"+ rank.getText() +"','"+salary.getText() + "','"+ type.getSelectedIndex() + "')";
        //System.out.println(sql);
        
        if(db.addNew(sql)){
            javax.swing.JOptionPane.showMessageDialog(null,"User has been added","Record added!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            admin.user_management();
            
            dispose();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null,"User has failed to be added","Record adding error!",javax.swing.JOptionPane.ERROR_MESSAGE);        
        }
    }
    class Action implements java.awt.event.ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            if( e.getSource() == cancel){
                setVisible( false );
                dispose();
            }else if( e.getSource() == next){
                try {
                    if(rs.next()){
                        populate(rs);
                    }                    
                    
                } catch (java.sql.SQLException ex) {
                   //Logger.getLogger(newItem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else  if( e.getSource() == prev){
                try {
                    if(rs.previous()){
                        populate(rs);
                    }
                } catch (java.sql.SQLException ex) {
                   // Logger.getLogger(newItem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else  if( e.getSource() == save || "save".equals(e.getActionCommand())){
                save();
            
            }else  if( e.getSource() == save || "update".equals(e.getActionCommand())){
                update();
            }else if ( e.getSource() == change_pass ){
                new changePass(emp_id.getText()).setVisible(true);
            }
        }
        
    }
}
