/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package posi.sys.customer;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import posi.sys.all.expeditors.database.db_connect;

/**
 *
 * @author Aquarius
 */

public class editCustPreference extends posi.sys.expeditors.popup {
    
    private posi.sys.all.expeditors.database.db_connect db = new db_connect();;
    
    private String index, item_index, item_name, pref_id;
    private double item_price;
    
    private int item_qty;
    public editCustPreference() {
        super(new java.awt.Dimension(350,570),"Customer preference");
        initComponents();
    }

   public editCustPreference(String index ){
        super(new java.awt.Dimension(350,570),"Customer preference");
        
        this.index = index;

        initComponents();
    }
        
    public editCustPreference(String index, Object[] info){
        super(new java.awt.Dimension(350,570),"Customer preference");
        
        this.index = index;
        
        pref_id = info[0].toString();
        item_index = info[1].toString();
        item_name = info[2].toString();
        item_price = Double.parseDouble(info[3].toString());
        item_qty = Integer.parseInt(info[4].toString());
        
        initComponents();
        
        fill_content();
        
        jButton1.setText("Update preference");
        jButton1.setActionCommand("update");
    }
    
    private void fill_content(){
        item_name_text.setText(""+item_name);
        item_id_text.setText(item_index);
        item_qty_text.setText(""+item_qty);
        item_price_text.setText(""+item_price);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        item_name_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cust_id_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        item_id_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        item_qty_text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        item_price_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Item name");

        item_name_text.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_name_textActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer Id");

        jLabel3.setText("Item Id");

        jLabel4.setText("Item qty");

        jLabel5.setText("Item price");

        jButton1.setText("Add preference");
        jButton1.setActionCommand("addNew");
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if( "addNew".equals(e.getActionCommand()) ){
                    String sql = "SELECT * FROM customer_preference WHERE customer_id = '" + index + "' AND preference_item_id = '"+item_index+"';";

                    Object data[][] = db.getData(sql);

                    if(data.length != 1){
                        String qty = item_qty_text.getText(); 
                        String price =  item_price_text.getText();
                        sql = "INSERT INTO customer_preference VALUES(NULL, '"+index+"', '"+item_index+"','"+qty+"','"+price+"')";

                        if( db.addNew(sql) ){
                            javax.swing.JOptionPane.showMessageDialog(null, "Record updated", "Response", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }else{
                        javax.swing.JOptionPane.showMessageDialog(null, "Record update failed!", "Response", JOptionPane.ERROR_MESSAGE);
                    }
                }else if(  "update".equals(e.getActionCommand()) ){
                    String sql = "UPDATE customer_preference SET preference_item_id='"+item_id_text.getText()+"', preference_item_qty='"+item_qty_text.getText()+"', preference_item_price='"+item_price_text.getText()+"' WHERE customer_id='"+index+"' AND preference_id='"+pref_id+"';";
                    
                    if( db.Update(sql) ){
                        javax.swing.JOptionPane.showMessageDialog(null, "Update successful!", "Response", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        javax.swing.JOptionPane.showMessageDialog(null, "Update failed", "Response", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
        
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        item_name_text.setEditable(true);// cust_id
        item_name_text.addKeyListener(new java.awt.event.KeyListener() {
            
            @Override
            public void keyTyped(KeyEvent e) { }
            @Override
            public void keyPressed(KeyEvent e) { 
                String text = item_name_text.getText();
                
                posi.sys.search.Search person = new posi.sys.search.Search(){                    
                    @Override
                    public void setTitle(String title) {
                        super.setTitle("Search customer");
                    }
                    @Override
                    public void setVisible(boolean b) {
                        if( b == false){
                            item_index = get_item_index();
                            item_name = get_item_name();
                            item_price = get_item_price();
                            
                            item_name_text.setText(""+item_name);
                            item_id_text.setText(item_index);
                            item_qty_text.setText(""+1);
                            item_price_text.setText(""+item_price);
                            
                            super.setVisible(false);
                        }else { super.setVisible(true);  }
                    }                    
                };
                
                person.setVisible(true);
                person.set_textfield_text(text);
                
                e.consume();
            }
            @Override
            public void keyReleased(KeyEvent e) { }
        });
        cust_id_text.setEditable(false);
        cust_id_text.setText(index);
        
        item_id_text.setEditable(false);
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(item_id_text, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cust_id_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(item_price_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(item_qty_text, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cust_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(item_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(item_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(item_qty_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(item_price_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void item_name_textActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editCustPreference(""+1, new Object[]{"2346","Item name","200","100"}).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField item_name_text;
    private javax.swing.JTextField cust_id_text;
    private javax.swing.JTextField item_id_text;
    private javax.swing.JTextField item_qty_text;
    private javax.swing.JTextField item_price_text;
    // End of variables declaration
}
